version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: ${DB_POSTGRESDB_HOST}
      DB_POSTGRESDB_DATABASE: postgres
      DB_POSTGRESDB_USER: n8nadmin
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_POSTGRESDB_SSL: "true"
      DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED: "false"
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}